// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoecSuuU1Iwl_ReXE1aUZhkvgwTFbxEIA',
    appId: '1:804424705027:web:7750bb8e553e3a9d935a36',
    messagingSenderId: '804424705027',
    projectId: 'flutterfirebaseeducated-3643c',
    authDomain: 'flutterfirebaseeducated-3643c.firebaseapp.com',
    storageBucket: 'flutterfirebaseeducated-3643c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKpyd-QaB5CGYNsIEFjYU0FuNbNQ-C-Ss',
    appId: '1:804424705027:android:ca870f0c78e7d48e935a36',
    messagingSenderId: '804424705027',
    projectId: 'flutterfirebaseeducated-3643c',
    storageBucket: 'flutterfirebaseeducated-3643c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6yzfTN1boGuXDF2ryT2fj4OBZI0-NBOo',
    appId: '1:804424705027:ios:872033f066959e99935a36',
    messagingSenderId: '804424705027',
    projectId: 'flutterfirebaseeducated-3643c',
    storageBucket: 'flutterfirebaseeducated-3643c.firebasestorage.app',
    iosBundleId: 'com.example.electricityPayment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6yzfTN1boGuXDF2ryT2fj4OBZI0-NBOo',
    appId: '1:804424705027:ios:872033f066959e99935a36',
    messagingSenderId: '804424705027',
    projectId: 'flutterfirebaseeducated-3643c',
    storageBucket: 'flutterfirebaseeducated-3643c.firebasestorage.app',
    iosBundleId: 'com.example.electricityPayment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoecSuuU1Iwl_ReXE1aUZhkvgwTFbxEIA',
    appId: '1:804424705027:web:cd09ebd6a6976841935a36',
    messagingSenderId: '804424705027',
    projectId: 'flutterfirebaseeducated-3643c',
    authDomain: 'flutterfirebaseeducated-3643c.firebaseapp.com',
    storageBucket: 'flutterfirebaseeducated-3643c.firebasestorage.app',
  );
}
